<?php

namespace Plugin\ChangeDeliveryDate\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\ChangeDeliveryDate\Entity\DeliveryDate;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * DeliveryDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryDateRepository extends AbstractRepository
{
    /**
     * DeliveryDateRepository constructor.
     * 
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(RegistryInterface $registry) {
        parent::__construct($registry, DeliveryDate::class);
    }

    /**
     * 最短お届け日・不可日を取得する.
     *
     * @param $type お届け最短日 0 / お届け不可日 1
     *
     * @return $textList
     */
    public function getDeliveryDate($type = 0)
    {

        $query = $this->createQueryBuilder('dd')
            ->where('dd.type = :type AND dd.date >= CURRENT_DATE()')
            ->setParameter('type', $type)
            ->getQuery();
        $deliveryDate = $query->getResult();

        // フォーマットをあわせる.
        $textList = '';
        foreach ($deliveryDate as $dateList) {
            $textList .= $dateList->getDate()->format('Y/m/d');
            if ($dateList->getDuration()) {
                $textList .= ',';
                $textList .= $dateList->getDuration();
            }
            $textList .= "\n";
        }

        return $textList;
    }

    /**
     * テーブルのデータを全て削除する.
     */
    public function deleteDelivDate($type)
    {
        $em = $this->getEntityManager();
        $deliveryDates = $this->findBy(array('type' => $type));

        foreach ($deliveryDates as $date) {
            $em->remove($date);
        }

        $em->flush();
    }
    




}
