<?php

namespace Customize\Repository;

use Eccube\Repository\AbstractRepository;
use Customize\Entity\Carriage;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CarriageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarriageRepository extends AbstractRepository
{

    /**
     * CarriageRepository constructor.
     */
    public function __construct(RegistryInterface $registry) {
        parent::__construct($registry, Carriage::class);
    }

    /**
     * 一覧を取得する　getList
     *
     * @return array|null
     */
    public function getList($id)
    {
        $query = $this->createQueryBuilder('c')
            ->orderBy('c.rule_min', 'ASC')
            ->where('c.payment_id = :id')
            ->setParameter('id', $id)
            ->getQuery();
        $carriages = $query->getResult();

        return $carriages;
    }

    /**
     * 代引手数料の削除.
     *
     * @param  int|\Customize\Entity\Carriage $carriage 税規約
     *
     * @throws NoResultException
     */
    public function delete($carriage)
    {
        if (!$carriage instanceof \Customize\Entity\Carriage) {
            $carriage = $this->find($carriage);
        }
        if (!$carriage) {
            throw new NoResultException();
        }
        $em = $this->getEntityManager();
        $em->remove($carriage);
        $em->flush();
    }


}
